// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(data PageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-30 flex h-16 w-full shrink-0 items-center gap-x-4 border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-zinc-950/80 px-4 shadow-sm sm:gap-x-6 sm:px-6 lg:px-8 transition-colors duration-200 backdrop-blur-md\"><!-- Desktop Sidebar Toggle --><button id=\"sidebar-desktop-toggle\" class=\"hidden lg:flex items-center justify-center h-9 w-9 text-zinc-400 hover:text-indigo-600 transition-colors rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-900\" onclick=\"toggleSidebar()\"><i data-lucide=\"panel-left\" class=\"h-5 w-5\"></i></button><!-- Mobile Sidebar Toggle --><button id=\"sidebar-mobile-toggle\" class=\"lg:hidden -m-2.5 p-2.5 text-slate-700 dark:text-slate-300\" onclick=\"openMobileSidebar()\"><span class=\"sr-only\">Open sidebar</span> <i data-lucide=\"menu\" class=\"h-6 w-6\"></i></button><div class=\"h-6 w-px bg-zinc-200 dark:bg-zinc-800 lg:hidden\" aria-hidden=\"true\"></div><div class=\"flex flex-1 gap-x-4 self-stretch lg:gap-x-6\"><!-- Breadcrumbs --><nav class=\"flex flex-1 items-center\" aria-label=\"Breadcrumb\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = breadcrumbs(data.CurrentPath).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</nav><div class=\"flex items-center gap-x-4 lg:gap-x-6\"><!-- Theme Switcher --><button onclick=\"toggleTheme()\" class=\"p-2 text-zinc-500 dark:text-zinc-400 hover:text-indigo-600 transition-colors rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-900\" title=\"Toggle theme\" id=\"theme-toggle\"><!-- Sun icon shows in light mode, Moon shows in dark mode --><i data-lucide=\"sun\" class=\"h-5 w-5 block dark:hidden\"></i> <i data-lucide=\"moon\" class=\"h-5 w-5 hidden dark:block\"></i></button><!-- Notifications (Mock) --><button type=\"button\" class=\"-m-2.5 p-2.5 text-slate-400 hover:text-indigo-600 relative transition-colors\"><span class=\"sr-only\">View notifications</span> <i data-lucide=\"bell\" class=\"h-6 w-6\"></i> <span class=\"absolute top-2.5 right-2.5 flex h-2 w-2 rounded-full bg-red-500 ring-2 ring-white dark:ring-slate-900 transition-all\"></span></button><!-- Separator --><div class=\"hidden lg:block lg:h-6 lg:w-px lg:bg-zinc-200 dark:lg:bg-zinc-800\" aria-hidden=\"true\"></div><!-- User Profile Dropdown --><div class=\"relative\"><button type=\"button\" class=\"-m-1.5 flex items-center p-1.5 group\" id=\"user-menu-button\" aria-expanded=\"false\" aria-haspopup=\"true\" onclick=\"toggleUserMenu()\"><span class=\"sr-only\">Open user menu</span><div class=\"h-8 w-8 rounded-full bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 flex items-center justify-center font-bold text-xs ring-2 ring-transparent group-hover:ring-indigo-100 dark:group-hover:ring-indigo-900/40 transition-all\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(UserInitials(data.UserName))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 63, Col: 36}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><span class=\"hidden lg:flex lg:items-center\"><span class=\"ml-4 text-sm font-semibold leading-6 text-slate-900 dark:text-slate-100\" aria-hidden=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.UserName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 66, Col: 127}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span> <i data-lucide=\"chevron-down\" class=\"ml-2 h-5 w-5 text-slate-400 group-hover:text-indigo-600 transition-colors\"></i></span></button><!-- Dropdown menu --><div id=\"user-menu-dropdown\" class=\"absolute right-0 z-10 mt-2.5 w-48 origin-top-right rounded-xl bg-white dark:bg-slate-800 py-2 shadow-xl ring-1 ring-slate-900/5 dark:ring-white/10 focus:outline-none hidden transition-all\" role=\"menu\" aria-orientation=\"vertical\" aria-labelledby=\"user-menu-button\"><div class=\"px-4 py-2 border-b border-slate-100 dark:border-slate-700/50 mb-1 lg:hidden\"><p class=\"text-xs font-semibold text-slate-400 uppercase tracking-wider\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.UserRole)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 79, Col: 95}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</p></div><a href=\"/profile\" class=\"block px-4 py-2 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700/50\" role=\"menuitem\">Your Profile</a> <a href=\"/settings\" class=\"block px-4 py-2 text-sm text-slate-700 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-700/50\" role=\"menuitem\">Settings</a><div class=\"my-1 h-px bg-slate-100 dark:bg-slate-700/50\"></div><a href=\"/logout\" class=\"block px-4 py-2 text-sm text-red-600 hover:bg-red-50 dark:hover:bg-red-900/10\" role=\"menuitem\">Sign out</a></div></div></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func breadcrumbs(path string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<nav class=\"flex overflow-hidden\" aria-label=\"Breadcrumb\"><ol role=\"list\" class=\"flex items-center space-x-2\"><li><div><a href=\"/\" class=\"text-slate-400 hover:text-indigo-600 transition-colors\"><i data-lucide=\"home\" class=\"h-5 w-5 shrink-0\"></i> <span class=\"sr-only\">Home</span></a></div></li>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, segment := range BuildBreadcrumbs(path) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<li><div class=\"flex items-center\"><i data-lucide=\"chevron-right\" class=\"h-4 w-4 shrink-0 text-slate-300 dark:text-slate-700 mx-1\"></i> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if segment.IsLast {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<span class=\"text-sm font-semibold text-slate-900 dark:text-slate-100 truncate max-w-[120px] sm:max-w-none\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(segment.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 108, Col: 130}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 templ.SafeURL
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(segment.Href))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 110, Col: 44}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" class=\"text-sm font-medium text-slate-400 hover:text-indigo-600 transition-colors truncate max-w-[100px] sm:max-w-none\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(segment.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/layout/navbar.templ`, Line: 111, Col: 23}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</ol></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
